apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: dev
type: Opaque
stringdata:
  POSTGRES_USER: changeme
  POSTGRES_PASSWORD: changeme
  POSTGRES_DB: changeme
  DATABASE_URL: changeme